#!/bin/sh
#
# count.sh
#
# Prints SLOC (source lines of code) statistics generated by SLOCCount and cloc (if found installed
# on the system).
#

which sloccount &> /dev/null && LANG=C sloccount src

echo
echo

which cloc &> /dev/null && cloc --force-lang=C++,hh src cmake *.txt *.sh
