#!/bin/bash
#
# count.sh
#
# Prints SLOC (source lines of code) statistics generated by SLOCCount and cloc (if found installed
# on the system).
#

set -e

which sloccount &> /dev/null && LC_ALL=C sloccount src

echo
echo

which cloc &> /dev/null && cloc --force-lang=C++,hh --force-lang=C++,h \
                                src cmake *.txt *.sh data/*/{glsl,lua,mission}

echo
echo

which tokei &> /dev/null && tokei src cmake *.txt *.sh data/*/{glsl,lua,mission}
